package com.thecoffeshop.Models;
// Generated Oct 24, 2018 11:35:31 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BilldetailId generated by hbm2java
 */
@Embeddable
public class BilldetailId implements java.io.Serializable {

	private String PId;
	private int biId;

	public BilldetailId() {
	}

	public BilldetailId(String PId, int biId) {
		this.PId = PId;
		this.biId = biId;
	}

	@Column(name = "P_ID", nullable = false, length = 7)
	public String getPId() {
		return this.PId;
	}

	public void setPId(String PId) {
		this.PId = PId;
	}

	@Column(name = "BI_ID", nullable = false)
	public int getBiId() {
		return this.biId;
	}

	public void setBiId(int biId) {
		this.biId = biId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BilldetailId))
			return false;
		BilldetailId castOther = (BilldetailId) other;

		return ((this.getPId() == castOther.getPId())
				|| (this.getPId() != null && castOther.getPId() != null && this.getPId().equals(castOther.getPId())))
				&& (this.getBiId() == castOther.getBiId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPId() == null ? 0 : this.getPId().hashCode());
		result = 37 * result + this.getBiId();
		return result;
	}

}
