package com.thecoffeshop.Models;
// Generated Oct 26, 2018 8:38:01 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Booktable generated by hbm2java
 */
@Entity
@Table(name = "booktable", catalog = "luanvan")
public class Booktable implements java.io.Serializable {

	private BooktableId id;
	private Customer customer;
	private Dinnertable dinnertable;
	private Employee employee;
	private Date btTimestart;
	private Boolean btStatus;
	private String createBy;
	private Date createAt;
	private String updateBy;
	private Date updateAt;
	private Boolean isDelete;
	private String deleteBy;
	private Date deleteAt;

	public Booktable() {
	}

	public Booktable(BooktableId id, Customer customer, Dinnertable dinnertable, Employee employee) {
		this.id = id;
		this.customer = customer;
		this.dinnertable = dinnertable;
		this.employee = employee;
	}

	public Booktable(BooktableId id, Customer customer, Dinnertable dinnertable, Employee employee, Date btTimestart,
			Boolean btStatus, String createBy, Date createAt, String updateBy, Date updateAt, Boolean isDelete,
			String deleteBy, Date deleteAt) {
		this.id = id;
		this.customer = customer;
		this.dinnertable = dinnertable;
		this.employee = employee;
		this.btTimestart = btTimestart;
		this.btStatus = btStatus;
		this.createBy = createBy;
		this.createAt = createAt;
		this.updateBy = updateBy;
		this.updateAt = updateAt;
		this.isDelete = isDelete;
		this.deleteBy = deleteBy;
		this.deleteAt = deleteAt;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cuId", column = @Column(name = "CU_ID", nullable = false, length = 7)),
			@AttributeOverride(name = "dnId", column = @Column(name = "DN_ID", nullable = false)),
			@AttributeOverride(name = "emId", column = @Column(name = "EM_ID", nullable = false, length = 7)) })
	public BooktableId getId() {
		return this.id;
	}

	public void setId(BooktableId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CU_ID", nullable = false, insertable = false, updatable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DN_ID", nullable = false, insertable = false, updatable = false)
	public Dinnertable getDinnertable() {
		return this.dinnertable;
	}

	public void setDinnertable(Dinnertable dinnertable) {
		this.dinnertable = dinnertable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EM_ID", nullable = false, insertable = false, updatable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "BT_TIMESTART", length = 8)
	public Date getBtTimestart() {
		return this.btTimestart;
	}

	public void setBtTimestart(Date btTimestart) {
		this.btTimestart = btTimestart;
	}

	@Column(name = "BT_STATUS")
	public Boolean getBtStatus() {
		return this.btStatus;
	}

	public void setBtStatus(Boolean btStatus) {
		this.btStatus = btStatus;
	}

	@Column(name = "CREATE_BY", length = 7)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_AT", length = 19)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Column(name = "UPDATE_BY", length = 7)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_AT", length = 19)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@Column(name = "IS_DELETE")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	@Column(name = "DELETE_BY", length = 7)
	public String getDeleteBy() {
		return this.deleteBy;
	}

	public void setDeleteBy(String deleteBy) {
		this.deleteBy = deleteBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DELETE_AT", length = 19)
	public Date getDeleteAt() {
		return this.deleteAt;
	}

	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}

}
