package com.thecoffeshop.Models;
// Generated Oct 26, 2018 8:38:01 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Categoryproduct generated by hbm2java
 */
@Entity
@Table(name = "categoryproduct", catalog = "luanvan")
public class Categoryproduct implements java.io.Serializable {

	private String cgPrdId;
	private String cgPrdName;
	private String createBy;
	private Date createAt;
	private String updateBy;
	private Date updateAt;
	private Boolean isDelete;
	private String deleteBy;
	private Date deleteAt;
	private Set<Product> products = new HashSet<Product>(0);

	public Categoryproduct() {
	}

	public Categoryproduct(String cgPrdId) {
		this.cgPrdId = cgPrdId;
	}

	public Categoryproduct(String cgPrdId, String cgPrdName, String createBy, Date createAt, String updateBy,
			Date updateAt, Boolean isDelete, String deleteBy, Date deleteAt, Set<Product> products) {
		this.cgPrdId = cgPrdId;
		this.cgPrdName = cgPrdName;
		this.createBy = createBy;
		this.createAt = createAt;
		this.updateBy = updateBy;
		this.updateAt = updateAt;
		this.isDelete = isDelete;
		this.deleteBy = deleteBy;
		this.deleteAt = deleteAt;
		this.products = products;
	}

	@Id

	@Column(name = "CG_PRD_ID", unique = true, nullable = false, length = 7)
	public String getCgPrdId() {
		return this.cgPrdId;
	}

	public void setCgPrdId(String cgPrdId) {
		this.cgPrdId = cgPrdId;
	}

	@Column(name = "CG_PRD_NAME")
	public String getCgPrdName() {
		return this.cgPrdName;
	}

	public void setCgPrdName(String cgPrdName) {
		this.cgPrdName = cgPrdName;
	}

	@Column(name = "CREATE_BY", length = 7)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_AT", length = 19)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Column(name = "UPDATE_BY", length = 7)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_AT", length = 19)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@Column(name = "IS_DELETE")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	@Column(name = "DELETE_BY", length = 7)
	public String getDeleteBy() {
		return this.deleteBy;
	}

	public void setDeleteBy(String deleteBy) {
		this.deleteBy = deleteBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DELETE_AT", length = 19)
	public Date getDeleteAt() {
		return this.deleteAt;
	}

	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoryproduct")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
