package com.thecoffeshop.Models;
// Generated Oct 24, 2018 11:35:31 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dinnertable generated by hbm2java
 */
@Entity
@Table(name = "dinnertable")
public class Dinnertable implements java.io.Serializable {

	private int dnId;
	private String dnName;
	private Integer dnCountchair;
	private String createBy;
	private Date createAt;
	private String updateBy;
	private Date updateAt;
	private Boolean isDelete;
	private String deleteBy;
	private Date deleteAt;
	private Set<Booktable> booktables = new HashSet<Booktable>(0);
	private Set<Bill> bills = new HashSet<Bill>(0);
	private Set<Tablestatusdetail> tablestatusdetails = new HashSet<Tablestatusdetail>(0);
	private Set<Image> images = new HashSet<Image>(0);

	public Dinnertable() {
	}

	public Dinnertable(int dnId) {
		this.dnId = dnId;
	}

	public Dinnertable(int dnId, String dnName, Integer dnCountchair, String createBy, Date createAt, String updateBy,
			Date updateAt, Boolean isDelete, String deleteBy, Date deleteAt, Set<Booktable> booktables, Set<Bill> bills,
			Set<Tablestatusdetail> tablestatusdetails, Set<Image> images) {
		this.dnId = dnId;
		this.dnName = dnName;
		this.dnCountchair = dnCountchair;
		this.createBy = createBy;
		this.createAt = createAt;
		this.updateBy = updateBy;
		this.updateAt = updateAt;
		this.isDelete = isDelete;
		this.deleteBy = deleteBy;
		this.deleteAt = deleteAt;
		this.booktables = booktables;
		this.bills = bills;
		this.tablestatusdetails = tablestatusdetails;
		this.images = images;
	}

	@Id

	@Column(name = "DN_ID", unique = true, nullable = false)
	public int getDnId() {
		return this.dnId;
	}

	public void setDnId(int dnId) {
		this.dnId = dnId;
	}

	@Column(name = "DN_NAME")
	public String getDnName() {
		return this.dnName;
	}

	public void setDnName(String dnName) {
		this.dnName = dnName;
	}

	@Column(name = "DN_COUNTCHAIR")
	public Integer getDnCountchair() {
		return this.dnCountchair;
	}

	public void setDnCountchair(Integer dnCountchair) {
		this.dnCountchair = dnCountchair;
	}

	@Column(name = "CREATE_BY", length = 7)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_AT", length = 19)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Column(name = "UPDATE_BY", length = 7)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_AT", length = 19)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@Column(name = "IS_DELETE")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	@Column(name = "DELETE_BY", length = 7)
	public String getDeleteBy() {
		return this.deleteBy;
	}

	public void setDeleteBy(String deleteBy) {
		this.deleteBy = deleteBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DELETE_AT", length = 19)
	public Date getDeleteAt() {
		return this.deleteAt;
	}

	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dinnertable")
	public Set<Booktable> getBooktables() {
		return this.booktables;
	}

	public void setBooktables(Set<Booktable> booktables) {
		this.booktables = booktables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dinnertable")
	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dinnertable")
	public Set<Tablestatusdetail> getTablestatusdetails() {
		return this.tablestatusdetails;
	}

	public void setTablestatusdetails(Set<Tablestatusdetail> tablestatusdetails) {
		this.tablestatusdetails = tablestatusdetails;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "dinnertables")
	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

}
