package com.thecoffeshop.Models;
// Generated Oct 24, 2018 11:35:31 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exportbill generated by hbm2java
 */
@Entity
@Table(name = "exportbill")
public class Exportbill implements java.io.Serializable {

	private String ebId;
	private Employee employee;
	private Materialdetail materialdetail;
	private Product product;
	private Date ebDateTime;
	private Integer ebQuantity;
	private String createBy;
	private Date createAt;
	private String updateBy;
	private Date updateAt;
	private Boolean isDelete;
	private String deleteBy;
	private Date deleteAt;

	public Exportbill() {
	}

	public Exportbill(String ebId) {
		this.ebId = ebId;
	}

	public Exportbill(String ebId, Employee employee, Materialdetail materialdetail, Product product, Date ebDateTime,
			Integer ebQuantity, String createBy, Date createAt, String updateBy, Date updateAt, Boolean isDelete,
			String deleteBy, Date deleteAt) {
		this.ebId = ebId;
		this.employee = employee;
		this.materialdetail = materialdetail;
		this.product = product;
		this.ebDateTime = ebDateTime;
		this.ebQuantity = ebQuantity;
		this.createBy = createBy;
		this.createAt = createAt;
		this.updateBy = updateBy;
		this.updateAt = updateAt;
		this.isDelete = isDelete;
		this.deleteBy = deleteBy;
		this.deleteAt = deleteAt;
	}

	@Id

	@Column(name = "EB_ID", unique = true, nullable = false, length = 7)
	public String getEbId() {
		return this.ebId;
	}

	public void setEbId(String ebId) {
		this.ebId = ebId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EM_ID")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MD_ID")
	public Materialdetail getMaterialdetail() {
		return this.materialdetail;
	}

	public void setMaterialdetail(Materialdetail materialdetail) {
		this.materialdetail = materialdetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "P_ID")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EB_DATE_TIME", length = 19)
	public Date getEbDateTime() {
		return this.ebDateTime;
	}

	public void setEbDateTime(Date ebDateTime) {
		this.ebDateTime = ebDateTime;
	}

	@Column(name = "EB_QUANTITY")
	public Integer getEbQuantity() {
		return this.ebQuantity;
	}

	public void setEbQuantity(Integer ebQuantity) {
		this.ebQuantity = ebQuantity;
	}

	@Column(name = "CREATE_BY", length = 7)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_AT", length = 19)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Column(name = "UPDATE_BY", length = 7)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_AT", length = 19)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@Column(name = "IS_DELETE")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	@Column(name = "DELETE_BY", length = 7)
	public String getDeleteBy() {
		return this.deleteBy;
	}

	public void setDeleteBy(String deleteBy) {
		this.deleteBy = deleteBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DELETE_AT", length = 19)
	public Date getDeleteAt() {
		return this.deleteAt;
	}

	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}

}
