package com.thecoffeshop.Models;
// Generated Oct 26, 2018 8:38:01 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", catalog = "luanvan")
public class Image implements java.io.Serializable {

	private int imgId;
	private String imgName;
	private Set<Employee> employees = new HashSet<Employee>(0);
	private Set<Dinnertable> dinnertables = new HashSet<Dinnertable>(0);
	private Set<Product> products = new HashSet<Product>(0);
	private Set<Material> materials = new HashSet<Material>(0);

	public Image() {
	}

	public Image(int imgId) {
		this.imgId = imgId;
	}

	public Image(int imgId, String imgName, Set<Employee> employees, Set<Dinnertable> dinnertables,
			Set<Product> products, Set<Material> materials) {
		this.imgId = imgId;
		this.imgName = imgName;
		this.employees = employees;
		this.dinnertables = dinnertables;
		this.products = products;
		this.materials = materials;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "IMG_ID", nullable = false)
	public int getImgId() {
		return this.imgId;
	}

	public void setImgId(int imgId) {
		this.imgId = imgId;
	}

	@Column(name = "IMG_NAME")
	public String getImgName() {
		return this.imgName;
	}

	public void setImgName(String imgName) {
		this.imgName = imgName;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "imageofemployee", catalog = "luanvan", joinColumns = {
			@JoinColumn(name = "IMG_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "EM_ID", nullable = false, updatable = false) })
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "imageofdinnertable", catalog = "luanvan", joinColumns = {
			@JoinColumn(name = "IMG_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "DN_ID", nullable = false, updatable = false) })
	public Set<Dinnertable> getDinnertables() {
		return this.dinnertables;
	}

	public void setDinnertables(Set<Dinnertable> dinnertables) {
		this.dinnertables = dinnertables;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "images")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "images")
	public Set<Material> getMaterials() {
		return this.materials;
	}

	public void setMaterials(Set<Material> materials) {
		this.materials = materials;
	}

}
