package com.thecoffeshop.Models;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Register generated by hbm2java
 */
@Entity
@Table(name = "register", catalog = "luanvan")
public class Register implements java.io.Serializable {

	private RegisterId id;
	private Employee employee;
	private Schedule schedule;
	private Date registerid;
	private Short result;
	private Date updateat;
	private Boolean isdelete;

	public Register() {
	}

	public Register(RegisterId id, Employee employee, Schedule schedule) {
		this.id = id;
		this.employee = employee;
		this.schedule = schedule;
	}

	public Register(RegisterId id, Employee employee, Schedule schedule, Date registerid, Short result, Date updateat,
			Boolean isdelete) {
		this.id = id;
		this.employee = employee;
		this.schedule = schedule;
		this.registerid = registerid;
		this.result = result;
		this.updateat = updateat;
		this.isdelete = isdelete;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "employeeid", column = @Column(name = "EMPLOYEEID", nullable = false, length = 7)),
			@AttributeOverride(name = "scheduleid", column = @Column(name = "SCHEDULEID", nullable = false, length = 7)) })
	public RegisterId getId() {
		return this.id;
	}

	public void setId(RegisterId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EMPLOYEEID", nullable = false, insertable = false, updatable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SCHEDULEID", nullable = false, insertable = false, updatable = false)
	public Schedule getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REGISTERID", length = 10)
	public Date getRegisterid() {
		return this.registerid;
	}

	public void setRegisterid(Date registerid) {
		this.registerid = registerid;
	}

	@Column(name = "RESULT", precision = 3, scale = 0)
	public Short getResult() {
		return this.result;
	}

	public void setResult(Short result) {
		this.result = result;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@Column(name = "ISDELETE")
	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

}
