package com.thecoffeshop.Models;
// Generated Oct 26, 2018 8:38:01 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RegisterId generated by hbm2java
 */
@Embeddable
public class RegisterId implements java.io.Serializable {

	private String emId;
	private String scId;

	public RegisterId() {
	}

	public RegisterId(String emId, String scId) {
		this.emId = emId;
		this.scId = scId;
	}

	@Column(name = "EM_ID", nullable = false, length = 7)
	public String getEmId() {
		return this.emId;
	}

	public void setEmId(String emId) {
		this.emId = emId;
	}

	@Column(name = "SC_ID", nullable = false, length = 7)
	public String getScId() {
		return this.scId;
	}

	public void setScId(String scId) {
		this.scId = scId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegisterId))
			return false;
		RegisterId castOther = (RegisterId) other;

		return ((this.getEmId() == castOther.getEmId()) || (this.getEmId() != null && castOther.getEmId() != null
				&& this.getEmId().equals(castOther.getEmId())))
				&& ((this.getScId() == castOther.getScId()) || (this.getScId() != null && castOther.getScId() != null
						&& this.getScId().equals(castOther.getScId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEmId() == null ? 0 : this.getEmId().hashCode());
		result = 37 * result + (getScId() == null ? 0 : this.getScId().hashCode());
		return result;
	}

}
