package com.thecoffeshop.Models;
// Generated Oct 26, 2018 8:38:01 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tablestatus generated by hbm2java
 */
@Entity
@Table(name = "tablestatus", catalog = "luanvan")
public class Tablestatus implements java.io.Serializable {

	private String tsId;
	private String tsName;
	private String createBy;
	private Date createAt;
	private String updateBy;
	private Date updateAt;
	private Boolean isDelete;
	private String deleteBy;
	private Date deleteAt;
	private Set<Tablestatusdetail> tablestatusdetails = new HashSet<Tablestatusdetail>(0);

	public Tablestatus() {
	}

	public Tablestatus(String tsId) {
		this.tsId = tsId;
	}

	public Tablestatus(String tsId, String tsName, String createBy, Date createAt, String updateBy, Date updateAt,
			Boolean isDelete, String deleteBy, Date deleteAt, Set<Tablestatusdetail> tablestatusdetails) {
		this.tsId = tsId;
		this.tsName = tsName;
		this.createBy = createBy;
		this.createAt = createAt;
		this.updateBy = updateBy;
		this.updateAt = updateAt;
		this.isDelete = isDelete;
		this.deleteBy = deleteBy;
		this.deleteAt = deleteAt;
		this.tablestatusdetails = tablestatusdetails;
	}

	@Id

	@Column(name = "TS_ID", unique = true, nullable = false)
	public String getTsId() {
		return this.tsId;
	}

	public void setTsId(String tsId) {
		this.tsId = tsId;
	}

	@Column(name = "TS_NAME")
	public String getTsName() {
		return this.tsName;
	}

	public void setTsName(String tsName) {
		this.tsName = tsName;
	}

	@Column(name = "CREATE_BY", length = 7)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_AT", length = 19)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Column(name = "UPDATE_BY", length = 7)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_AT", length = 19)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@Column(name = "IS_DELETE")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	@Column(name = "DELETE_BY", length = 7)
	public String getDeleteBy() {
		return this.deleteBy;
	}

	public void setDeleteBy(String deleteBy) {
		this.deleteBy = deleteBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DELETE_AT", length = 19)
	public Date getDeleteAt() {
		return this.deleteAt;
	}

	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tablestatus")
	public Set<Tablestatusdetail> getTablestatusdetails() {
		return this.tablestatusdetails;
	}

	public void setTablestatusdetails(Set<Tablestatusdetail> tablestatusdetails) {
		this.tablestatusdetails = tablestatusdetails;
	}

}
