package com.thecoffeshop.Models;
// Generated Nov 6, 2018 1:02:23 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tablestatusdetail generated by hbm2java
 */
@Entity
@Table(name = "tablestatusdetail", catalog = "luanvan")
public class Tablestatusdetail implements java.io.Serializable {

	private TablestatusdetailId id;
	private Dinnertable dinnertable;
	private Tablestatus tablestatus;
	private String createby;
	private Date createat;
	private String updateby;
	private Date updateat;
	private Boolean isdelete;
	private String deleteby;
	private Date deleteat;

	public Tablestatusdetail() {
	}

	public Tablestatusdetail(TablestatusdetailId id, Dinnertable dinnertable, Tablestatus tablestatus) {
		this.id = id;
		this.dinnertable = dinnertable;
		this.tablestatus = tablestatus;
	}

	public Tablestatusdetail(TablestatusdetailId id, Dinnertable dinnertable, Tablestatus tablestatus, String createby,
			Date createat, String updateby, Date updateat, Boolean isdelete, String deleteby, Date deleteat) {
		this.id = id;
		this.dinnertable = dinnertable;
		this.tablestatus = tablestatus;
		this.createby = createby;
		this.createat = createat;
		this.updateby = updateby;
		this.updateat = updateat;
		this.isdelete = isdelete;
		this.deleteby = deleteby;
		this.deleteat = deleteat;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dinnertableid", column = @Column(name = "DINNERTABLEID", nullable = false)),
			@AttributeOverride(name = "tablestatusid", column = @Column(name = "TABLESTATUSID", nullable = false)) })
	public TablestatusdetailId getId() {
		return this.id;
	}

	public void setId(TablestatusdetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DINNERTABLEID", nullable = false, insertable = false, updatable = false)
	public Dinnertable getDinnertable() {
		return this.dinnertable;
	}

	public void setDinnertable(Dinnertable dinnertable) {
		this.dinnertable = dinnertable;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TABLESTATUSID", nullable = false, insertable = false, updatable = false)
	public Tablestatus getTablestatus() {
		return this.tablestatus;
	}

	public void setTablestatus(Tablestatus tablestatus) {
		this.tablestatus = tablestatus;
	}

	@Column(name = "CREATEBY", length = 7)
	public String getCreateby() {
		return this.createby;
	}

	public void setCreateby(String createby) {
		this.createby = createby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEAT", length = 19)
	public Date getCreateat() {
		return this.createat;
	}

	public void setCreateat(Date createat) {
		this.createat = createat;
	}

	@Column(name = "UPDATEBY", length = 7)
	public String getUpdateby() {
		return this.updateby;
	}

	public void setUpdateby(String updateby) {
		this.updateby = updateby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@Column(name = "ISDELETE")
	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	@Column(name = "DELETEBY", length = 7)
	public String getDeleteby() {
		return this.deleteby;
	}

	public void setDeleteby(String deleteby) {
		this.deleteby = deleteby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DELETEAT", length = 19)
	public Date getDeleteat() {
		return this.deleteat;
	}

	public void setDeleteat(Date deleteat) {
		this.deleteat = deleteat;
	}

}
